"""Change type return_date

Revision ID: 4c34b39df8c8
Revises: 
Create Date: 2024-12-13 18:39:49.073242

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c34b39df8c8"
down_revision: Union[str, None] = "5dbb0ea8f37a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("borrow", "return_date", existing_type=sa.DATE(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("borrow", "return_date", existing_type=sa.DATE(), nullable=False)
    # ### end Alembic commands ###
