"""Create models...

Revision ID: a8dda609992b
Revises: d1226d97dfc3
Create Date: 2024-12-10 21:05:48.945453

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8dda609992b"
down_revision: Union[str, None] = "d1226d97dfc3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_author_id"), "author", ["id"])
    op.create_unique_constraint(op.f("uq_book_id"), "book", ["id"])
    op.create_unique_constraint(op.f("uq_borrow_id"), "borrow", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_borrow_id"), "borrow", type_="unique")
    op.drop_constraint(op.f("uq_book_id"), "book", type_="unique")
    op.drop_constraint(op.f("uq_author_id"), "author", type_="unique")
    # ### end Alembic commands ###
